In [24]:
import pandas as pd
dataFile = pd.read_csv('homework.csv')

1.Ознайомитися з датасетом зі списком автомобілів Automobile Data Set

In [25]:
dataFile[:20]

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
12,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
13,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565
14,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
15,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
16,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
17,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
18,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
19,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575

In [26]:
dataFile.info()
dataFile.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
3              204 non-null int64
?              204 non-null object
alfa-romero    204 non-null object
gas            204 non-null object
std            204 non-null object
two            204 non-null object
convertible    204 non-null object
rwd            204 non-null object
front          204 non-null object
88.60          204 non-null float64
168.80         204 non-null float64
64.10          204 non-null float64
48.80          204 non-null float64
2548           204 non-null int64
dohc           204 non-null object
four           204 non-null object
130            204 non-null int64
mpfi           204 non-null object
3.47           204 non-null object
2.68           204 non-null object
9.00           204 non-null float64
111            204 non-null object
5000           204 non-null object
21             204 non-null int64
27             204 non-null int64
13495          204 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.5+ KB

,3,88.60,168.80,64.10,48.80,2548,130,9.00,21,27
count,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,0.823529,98.806373,174.075000,65.916667,53.749020,2555.602941,126.892157,10.148137,25.240196,30.769608
std,1.239035,5.994144,12.362123,2.146716,2.424901,521.960820,41.744569,3.981000,6.551513,6.898337
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.075000,52.000000,2145.000000,97.000000,8.575000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,119.500000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.200000,66.900000,55.500000,2939.250000,142.000000,9.400000,30.000000,34.500000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

2. Виділити і проаналізувати числові атрибути даної вибірки

In [27]:
dataFile[:20].select_dtypes(include=['float64', 'int64'])

    3  88.60  168.80  64.10  48.80  2548  130  9.00  21  27
0   3   88.6   168.8   64.1   48.8  2548  130   9.0  21  27
1   1   94.5   171.2   65.5   52.4  2823  152   9.0  19  26
2   2   99.8   176.6   66.2   54.3  2337  109  10.0  24  30
3   2   99.4   176.6   66.4   54.3  2824  136   8.0  18  22
4   2   99.8   177.3   66.3   53.1  2507  136   8.5  19  25
5   1  105.8   192.7   71.4   55.7  2844  136   8.5  19  25
6   1  105.8   192.7   71.4   55.7  2954  136   8.5  19  25
7   1  105.8   192.7   71.4   55.9  3086  131   8.3  17  20
8   0   99.5   178.2   67.9   52.0  3053  131   7.0  16  22
9   2  101.2   176.8   64.8   54.3  2395  108   8.8  23  29
10  0  101.2   176.8   64.8   54.3  2395  108   8.8  23  29
11  0  101.2   176.8   64.8   54.3  2710  164   9.0  21  28
12  0  101.2   176.8   64.8   54.3  2765  164   9.0  21  28
13  1  103.5   189.0   66.9   55.7  3055  164   9.0  20  25
14  0  103.5   189.0   66.9   55.7  3230  209   8.0  16  22
15  0  103.5   193.8   67.9   53.7  3380  209   8.0  16  22
16  0  110.0   197.0   70.9   56.3  3505  209   8.0  15  20
17  2   88.4   141.1   60.3   53.2  1488   61   9.5  47  53
18  1   94.5   155.9   63.6   52.0  1874   90   9.6  38  43
19  0   94.5   158.8   63.6   52.0  1909   90   9.6  38  43

3. Категоріальні атрибути

4.Проаналізувати кількість відсутніх даних для кожного атрибута.
Деякі атрибути не відображаються, тому знайдемо такі дані.

In [28]:
dataFile.isin(['?']).any()

3              False
?               True
alfa-romero    False
gas            False
std            False
two             True
convertible    False
rwd            False
front          False
88.60          False
168.80         False
64.10          False
48.80          False
2548           False
dohc           False
four           False
130            False
mpfi           False
3.47            True
2.68            True
9.00           False
111             True
5000            True
21             False
27             False
13495           True
dtype: bool

Атрибути з пропущеними даними:

normalized-losses 41

num-of-doors 2

bore 4

stroke 4

horsepower 2

peak-rpm 2

price 4

6.Зробити кореляцію для числових атрибутів. Знайти колінеарні атрибути (якщо такі є), описати їх і вказати, якими атрибутами можна знехтувати.

In [29]:
dataFile.corr()

,3,88.60,168.80,64.10,48.80,2548,130,9.00,21,27
3,1.000000,-0.525095,-0.356792,-0.227799,-0.533078,-0.229281,-0.107229,-0.177413,-0.030557,0.039598
88.60,-0.525095,1.000000,0.877612,0.795115,0.582603,0.781763,0.573989,0.249199,-0.479633,-0.552897
168.80,-0.356792,0.877612,1.000000,0.841199,0.491969,0.878090,0.683830,0.157913,-0.673251,-0.706635
64.10,-0.227799,0.795115,0.841199,1.000000,0.274075,0.868493,0.737042,0.180287,-0.647177,-0.681169
48.80,-0.533078,0.582603,0.491969,0.274075,1.000000,0.298429,0.068577,0.261036,-0.055659,-0.113995
2548,-0.229281,0.781763,0.878090,0.868493,0.298429,1.000000,0.850611,0.151372,-0.758238,-0.798088
130,-0.107229,0.573989,0.683830,0.737042,0.068577,0.850611,1.000000,0.029083,-0.654101,-0.677775
9.00,-0.177413,0.249199,0.157913,0.180287,0.261036,0.151372,0.029083,1.000000,0.324186,0.264677
21,-0.030557,-0.479633,-0.673251,-0.647177,-0.055659,-0.758238,-0.654101,0.324186,1.000000,0.971311
27,0.039598,-0.552897,-0.706635,-0.681169,-0.113995,-0.798088,-0.677775,0.264677,0.971311,1.000000

7.Описати нормалізацію (слайд з конструюванням атрибутів) числових атрибутів.

При нормалізації атрибутів даної вибірки, значення, length, width, height які можна перетворити на один атрибут volume якщо перемножити їх значення.